### ISSUE TITLE
[Java-Spring-server] Syntax error: missing comma

### ISSUE THREAD

**Issue by simonlinj** [swagger-api/swagger-codegen#8976]
##### Description

The generated server code contains a syntax error.

##### Swagger-codegen version

swagger-codegen 3.0.3 installed with brew 

##### Swagger declaration file content or url

http://petstore.swagger.io/v2/swagger.yaml

##### Command line used for generation
```
swagger-codegen generate \
  -i http://petstore.swagger.io/v2/swagger.yaml \
  -l spring \
  -o samples/server/petstore/springboot
```
##### Related issues/PRs

probably #8631

##### Actual generated code
UserApi.java
```java
    default ResponseEntity<Void> updateUser(@ApiParam(value = "Updated user object" ,required=true )  @Valid @RequestBody User body@ApiParam(value = "name that need to be updated",required=true) @PathVariable("username") String username) {
```
Expected generated code
##### 
UserApi.java
```java 
    default ResponseEntity<Void> updateUser(@ApiParam(value = "Updated user object" ,required=true )  @Valid @RequestBody User body,
                                            @ApiParam(value = "name that need to be updated",required=true) @PathVariable("username") String username) {
```

**Comment by simonlinj** [comment]
its a regression bug. worked in v3.0.2

**Comment by HugoMario** [comment]
Hello @simonlinj 

I added a PR fixing this, can you please verify it when you have a chance?

**Comment by simonlinj** [comment]
still not fixed on `3.0.4-SNAPSHOT`

```
/Users/simon/test/spring-boot-docker/build/swagger-code-api/src/main/java/example/api/UserApi.java:164: error: illegal start of expression
    default ResponseEntity<Void> updateUser(@ApiParam(value = "Updated user object" ,required=true )  @Valid @RequestBody User body@ApiParam(value = "name that need to be updated",required=true) @PathVariable("username") String username) {
```

**Comment by HugoMario** [comment]
@simonlinj 
just added a new PR, you can try it with https://oss.sonatype.org/content/repositories/snapshots/io/swagger/codegen/v3/swagger-codegen-cli/3.0.4-SNAPSHOT/swagger-codegen-cli-3.0.4-20181211.195230-10.jar

If there is something wrong please let me know and i´ll fix as soon as possible.

**Comment by simonlinj** [comment]
@HugoMario 
it's fixed now, hope you can release it soon.  thank you very much!
