### PR TITLE
Reverted JsonUtil.mustache for JavaClientCodegen after PR #726.

### PR DESCRIPTION
**Pull request by tomtit**
Generated Java sample for the Pet Store is broken after the PR #726:
```
$ ./bin/java-petstore.sh ; cd samples/client/petstore/java; mvn clean package
...
[INFO] 9 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.936s
[INFO] Finished at: Fri May 08 12:32:56 UTC 2015
[INFO] Final Memory: 13M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project swagger-java-client: Compilation failure: Compilation failure:
[ERROR] /home/swagger.io/swagger-codegen/samples/client/petstore/java/src/main/java/io/swagger/client/JsonUtil.java:[3,22] error: package com.google.gson does not exist
[ERROR] /home/swagger.io/swagger-codegen/samples/client/petstore/java/src/main/java/io/swagger/client/JsonUtil.java:[4,22] error: package com.google.gson does not exist
[ERROR] /home/swagger.io/swagger-codegen/samples/client/petstore/java/src/main/java/io/swagger/client/JsonUtil.java:[7,16] error: cannot find symbol
[ERROR] class JsonUtil
[ERROR] /home/swagger.io/swagger-codegen/samples/client/petstore/java/src/main/java/io/swagger/client/JsonUtil.java:[14,16] error: cannot find symbol
[ERROR] class JsonUtil
[ERROR] /home/swagger.io/swagger-codegen/samples/client/petstore/java/src/main/java/io/swagger/client/ApiInvoker.java:[134,36] error: cannot find symbol
[ERROR] class JsonUtil
[ERROR] /home/swagger.io/swagger-codegen/samples/client/petstore/java/src/main/java/io/swagger/client/ApiInvoker.java:[135,42] error: cannot find symbol
[ERROR] class JsonUtil
[ERROR] /home/swagger.io/swagger-codegen/samples/client/petstore/java/src/main/java/io/swagger/client/ApiInvoker.java:[145,23] error: cannot find symbol
[ERROR] class JsonUtil
[ERROR] /home/swagger.io/swagger-codegen/samples/client/petstore/java/src/main/java/io/swagger/client/ApiInvoker.java:[156,23] error: cannot find symbol
[ERROR] class JsonUtil
[ERROR] /home/swagger.io/swagger-codegen/samples/client/petstore/java/src/main/java/io/swagger/client/JsonUtil.java:[10,22] error: cannot find symbol
```

### CODE REVIEW

**Comment by who** [comment]
Oops, sorry about this - In https://github.com/swagger-api/swagger-codegen/pull/726 I committed the regular Java jsonutil as well as the android-java jsonutil.  This was unintentional, as PR https://github.com/swagger-api/swagger-codegen/pull/726 was only meant to change the android-java stack.

+1 to this PR being merge.

**Comment by wing328** [comment]
+1

I was able to repeat the issue with the develop_2.0 branch and this PR resolves the issue.
