### ISSUE TITLE
[Python] AttributeError: module 'typing' has no attribute 'Type' in python 3.5.1

### ISSUE THREAD

**Issue by easysun** [swagger-api/swagger-codegen#7361]
##### Description
In python 3.5.1, type `python -m swagger_server` will get the following error:
**File "/swagger-codegen/samples/server/petstore/flaskConnexion/swagger_server/models/base_model_.py", line 21, in Model
    def from_dict(cls: typing.Type[T], dikt) -> T:
AttributeError: module 'typing' has no attribute 'Type'**

##### Swagger-codegen version

2.3.0

##### Suggest a fix/enhancement

1. edit `swagger_server/models/base_model_.py`
2. add `from typing import TypeVar, Generic` after `import typing`
3. replace the 22nd line as below
>   def from_dict(cls: typing.~Type~[T], dikt) -> T: 
>   def from_dict(cls: typing.**Generic**[T], dikt) -> T:
4. type `python -m swagger_server` to start the service and you would see: 
`* Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)`

**Comment by cbornet** [comment]
Type and Generic don’t have the same meaning. Can you check with python 3.5.4 ?

**Comment by ioggstream** [comment]
Works with Python 3.6.

**Comment by xuzhenglun** [comment]
any update?

**Comment by ioggstream** [comment]
Try with python 3.6 ;)

**Comment by sloria** [comment]
The typing module was upgraded in Python 3.5.4: https://bugs.python.org/issue28556 . Upgrading to a newer patch version should fix the issue.
