### ISSUE TITLE
[Java] Compilation error with model containing with Map<String, Set<enum>>

### ISSUE THREAD

**Issue by jennifergarcia** [swagger-api/swagger-codegen#3780]
##### Description
I am able to run swagger codegen with 2.1.5 but there are bugs which break codgen until master when you have a model containing a container with an enum embedded in another container.

##### Swagger-codegen version
Worked in 2.1.5 as the enum evaluated to just a string
2.1.6 - broken for other reasons
2.2.2-SNAPSHOT, still broken

##### Swagger declaration file content or url
Java class with annotation 

```java
@ApiModel (value = "MyModel", description = "My model description")
public class MyModel {

    @ApiModel
    public enum MyEnum {
        VALUE1,VALUE2,VALUE3
    }

    @JsonProperty("my_property")
    @ApiModelProperty (value = "my property description")
    private Map<String, Set<MyEnum>> breakingProperty;

    @JsonCreator
    public MyModel(@JsonProperty ("my_property") Map<String, Set<MyEnum>> property) {
        breakingProperty = breakingProperty;
    }
}

```json
    "MyModel" : {
      "type" : "object",
      "properties" : {
        "my_property" : {
          "type" : "object",
          "description" : "my property description",
          "additionalProperties" : {
            "type" : "array",
            "uniqueItems" : true,
            "items" : {
              "type" : "string",
              "enum" : [ "VALUE1", "VALUE2", "VALUE3" ]
            }
          }
        }
      }
```
##### Command line used for generation

Using the maven plugin with the java jersey2 libraries and joda as a date library

##### Steps to reproduce

1) Run codegen on the spec

The following code is produced:

##### Related issues
https://github.com/swagger-api/swagger-codegen/issues/3450

This fixed an array with an enum but not when it is nested.

##### Suggest a Fix

At this time, I don't have one, I need to do some more work to step through and debug the code.  Basically something in the template is causing the generated code to produce an InnerEnum reference without defining it.  The original enum never gets generated for some reason.  Also there is an issue referencing it as well.  I'm not 100% sure this is a problem with codegen, it also might be with generating the spec from the annotation library as well.  When I get a chance, I will be trying to isolate that.
