### ISSUE TITLE
hasExplicitTimeZone error for date-time format in swaggergen 3.0.26

### ISSUE THREAD

**Issue by pbthorste** [swagger-api/swagger-codegen#11040]
##### Description
When generating code, the following error pops up:

```
Exception in thread "Thread-0" java.lang.NoSuchMethodError: 'boolean com.fasterxml.jackson.databind.SerializationConfig.hasExplicitTimeZone()'
        at com.fasterxml.jackson.datatype.jsr310.ser.InstantSerializerBase.formatValue(InstantSerializerBase.java:144)
        at com.fasterxml.jackson.datatype.jsr310.ser.InstantSerializerBase.serialize(InstantSerializerBase.java:103)
        at com.fasterxml.jackson.datatype.jsr310.ser.InstantSerializerBase.serialize(InstantSerializerBase.java:43)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
```

This was not an issue in earlier versions of swaggergen, but started happening after upgrading to 3.0.26

##### Swagger-codegen version

3.0.26

##### Swagger declaration file content or url

```yaml
openapi: 3.0.0

paths:
  /:
    get:
      summary: "Example"
      parameters:
        #query
        - $ref: "#/components/parameters/dateTimeFrom"
      #body
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  parameters:
    dateTimeFrom:
      name: dateTimeFrom
      in: "query"
      description: |
      schema:
        $ref: "#/components/schemas/myDateTime"

  schemas:
    myDateTime:
      description: The date and time
      type: string
      format: date-time
      example: "2021-04-30T09:12:03.427Z"
```

##### Command line used for generation

```
java -jar swagger-codegen-cli-3.0.26.jar generate -o out -l java -i ./swagger.yaml
```

##### Steps to reproduce

Run the command line command given with the swaggerfile

##### Workaround

In the given swagger example, if you remove the timezone from the 'example' bit, the issue does not occur. So change the 'myDateTime' to this:

```yaml
myDateTime:
      description: The date and time
      type: string
      format: date-time
      example: "2021-04-30T09:12:03.427"
```

**Comment by am-houtkooper** [comment]
The error apparently comes from using two different versions of jackson databind.

swagger-codegen 3.0.26 uses:

1. swagger-core 1.6.2 which uses jackson 2.11.1
1. swagger-parser 1.0.55 which uses swagger-core 1.6.1 which uses jackson 2.10.1

Two ways to fix this:

1. Downgrade to swagger-core 1.6.1, or, if that's not feasible
2. Upgrade swagger-parser and also swagger-compat-spec-parser to use swagger-core 1.6.2

**Comment by pbthorste** [comment]
Issue is fixed in swagger-codegen 3.0.27
