### PR TITLE
Fix environment variable support in successive Maven plugin executions

### PR DESCRIPTION
**Pull request by sadimusi**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

System properties were retained across multiple successive executions,
resulting in unpredictable behavior. Property values are now properly reset
to their original value after plugin execution.

See #5350

### CODE REVIEW

**Comment by sadimusi** [comment]
I just want to note, that the travis build failed due to a npm connection issue.

File: modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java [hunk 1]
```diff
@@ -431,5 +434,13 @@ public void execute() throws MojoExecutionException {
             String sourceJavaFolder = output.toString() + "/" + sourceFolder;
             project.addCompileSourceRoot(sourceJavaFolder);
         }
+
```
Comment (wing328) [inline modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java]: @sadimusi Suggestion: A 1-liner explaining what the block does would be nice

**Comment by wing328** [comment]
@sadimusi I've restarted the job and all CI tests pass.

**Comment by sadimusi** [comment]
Added a brief explanation.

**Comment by wing328** [comment]
@sadimusi thanks for adding more comments to the code. The change looks good to me.

**Comment by wing328** [comment]
After merging this into master, CI reports the following errors:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project swagger-codegen-maven-plugin: Compilation failure
[ERROR] /private/tmp/swagger-codegen/modules/swagger-codegen-maven-plugin/src/main/java/io/swagger/codegen/plugin/CodeGenMojo.java:[456,47] cannot find symbol
[ERROR] symbol:   variable originalEnvironmentVariables
[ERROR] location: class io.swagger.codegen.plugin.CodeGenMojo
```

I'm working on a fix to move `originalEnvironmentVariables` to a private member.

**Comment by wing328** [comment]
Fixed via d3ac4b6
