### PR TITLE
Add templates for async client Retrofit2 in Java Play Framework 2.6

### PR DESCRIPTION
**Pull request by ignaciomolina**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas @JFCote @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger

### Description of the PR

Add templates to support Play Framework version 2.6 with async clients using Retrofit2

### CODE REVIEW

**Comment by tzimisce012** [comment]
Good Job there 👍

**Comment by JFCote** [comment]
I will have a look at this tomorrow. Thanks

File: modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/play26/ApiClient.mustache [hunk 1]
```diff
@@ -0,0 +1,136 @@
...
+
+    public ApiClient() {
+        // Setup authentications (key: authentication name, value: authentication).
+        authentications = new HashMap<>();{{#authMethods}}{{#isBasic}}
+        // authentications.put("{{name}}", new HttpBasicAuth());{{/isBasic}}{{#isApiKey}}
+        authentications.put("{{name}}", new ApiKeyAuth({{#isKeyInHeader}}"header"{{/isKeyInHeader}}{{^isKeyInHeader}}"query"{{/isKeyInHeader}}, "{{keyParamName}}"));{{/isApiKey}}{{#isOAuth}}
+        // authentications.put("{{name}}", new OAuth());{{/isOAuth}}{{/authMethods}}
+        // Prevent the authentications from being modified.
+        authentications = Collections.unmodifiableMap(authentications);
+
```
Comment (JFCote) [inline modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/play26/ApiClient.mustache]: remove empty line

File: modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/play26/Play26CallAdapterFactory.mustache [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+ * Creates {@link CallAdapter} instances that convert {@link Call} into {@link java.util.concurrent.CompletionStage}
+ */
+public class Play26CallAdapterFactory extends CallAdapter.Factory {
+
+    private Function<RuntimeException, RuntimeException> exceptionConverter = Function.identity();
+
+    public Play26CallAdapterFactory() {
+    }
+
+    public Play26CallAdapterFactory(
```
Comment (JFCote) [inline modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/play26/Play26CallAdapterFactory.mustache]: why is there a carriage return here?

**Comment by JFCote** [comment]
@ignaciomolina For my curiosity only, what is the use of this client and what is the "link" to play framework. I'm the main contributor to the Play Framework server stub codegen and to connect to it, we use java client, c# client, typescript client but I would like to know the advantage of using this one. Thanks :)

File: modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/play26/Play26CallAdapterFactory.mustache [hunk 3]
```diff
@@ -18,8 +18,7 @@ public class Play26CallAdapterFactory extends CallAdapter.Factory {
 
     private Function<RuntimeException, RuntimeException> exceptionConverter = Function.identity();
 
-    public Play26CallAdapterFactory() {
-    }
+    public Play26CallAdapterFactory() { }
```
Comment (JFCote) [inline modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/play26/Play26CallAdapterFactory.mustache]: it wasn't that constructor, it was the one below with a parameter :)

**Comment by tzimisce012** [comment]
Well, this client will allow us to use `WSClient` that is an asynchronous client. A regular java client will be blocking and we will have to set a specific thread pool just for him.

File: modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/play26/Play26CallAdapterFactory.mustache (hunk 3 above)
Comment (ignaciomolina) [reply modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/play26/Play26CallAdapterFactory.mustache]: :+1:

**Comment by lukoyanov** [comment]
> For my curiosity only, what is the use of this client and what is the "link" to play framework.
@JFCote the only connection of ApiClient.java to play! framework is that internally adds callFactory & callAdapterFactory that uses WSClient to discatch api calls.

File: modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java [hunk 4]
```diff
@@ -67,7 +68,7 @@ public JavaClientCodegen() {
         cliOptions.add(CliOption.newBoolean(USE_RX_JAVA2, "Whether to use the RxJava2 adapter with the retrofit2 library."));
         cliOptions.add(CliOption.newBoolean(PARCELABLE_MODEL, "Whether to generate models for Android that implement Parcelable with the okhttp-gson library."));
         cliOptions.add(CliOption.newBoolean(USE_PLAY_WS, "Use Play! Async HTTP client (Play WS API)"));
-        cliOptions.add(CliOption.newString(PLAY_VERSION, "Version of Play! Framework (possible values \"play24\", \"play25\")"));
```
Comment (cbornet) [inline modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java]: Do we really have to support each and every version of Play ? This is getting really messy...

Comment (tzimisce012) [reply modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java]: Since each change of version of play means that everything changes completly, it is so far necessary to keep all of them...

Comment (cbornet) [reply modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java]: This is a retrofit generator, not a Play one. Also it seems to me that a lot of templates are just duplicated between 2.5 and 2.6

Comment (tzimisce012) [reply modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java]: I am glad that the client generator for play is using retrofit. 

There is a folder called common where all duplicated templates between versions 2.5 and 2.6 should be. If there is a duplicated template not located there, this PR should be rejected

Comment (cbornet) [reply modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java]: I looked and it seems 2.6 is almost entirely duplicate of 2.5 (minor changes but that probably also work for 2.5)
I also think it should be possible to have common templates between 2.4 and 2.5 with minimal work which would greatly simplify the Java generator code.
And 2.5 seems to introduce adapters for CompletionStage (CompletableFuture) which are already part of retrofit-adapters so they could probably be removed.

Comment (tzimisce012) [reply modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java]: Those minor changes don't work on play 2.5 (100% sure)

Comment (cbornet) [reply modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java]: Eventually, wouldn't Play developers prefer to get scala.concurrent.Future rather than CompletionStage/CompletableFuture ?

Comment (cbornet) [reply modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java]: > Those minor changes don't work on play 2.5 (100% sure)

OK so they should be applied by mustache tags, not by duplicating the templates.

Comment (tzimisce012) [reply modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java]: Meanwhile there are 2 different versions of Play (Scala and Java), we should have an autogenerated client for both versions. 

I don't know what could be the reason to program play with java. Moreover, I don't know the reason to program on play at all 🍡

Comment (ignaciomolina) [reply modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java]: ok, I have merged the play version templates

Comment (cbornet) [reply modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java]: :+1: great work !

**Comment by wing328** [comment]
I ran `mvn test` in the folder `samples/client/petstore/java/retrofit2-play26` but got the following errors:
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /private/tmp/swagger-codegen/samples/client/petstore/java/retrofit2-play26/src/main/java/io/swagger/client/PlayCallFactory.java:[141,56] cannot find symbol
  symbol:   method setRequestFilter(play.libs.ws.WSRequestFilter)
  location: variable wsRequest of type play.libs.ws.WSRequest
[ERROR] /private/tmp/swagger-codegen/samples/client/petstore/java/retrofit2-play26/src/main/java/io/swagger/client/PlayCallFactory.java:[178,36] cannot find symbol
  symbol:   method getSingleHeader(java.lang.String)
  location: variable r of type play.libs.ws.WSResponse
```

Did you get these errors when running `mvn test` locally in your machine?

**Comment by ignaciomolina** [comment]
Sorry @wing328, I hadn't seen your comment, the answer is No, I don't get those errors when running `mvn test` locally

**Comment by ignaciomolina** [comment]
Sorry @wing328, you were right, I already fix all the issues and now it compiles fine in Maven, Sbt and Gradle
