### ISSUE TITLE
Cannot find module '../service/{module}'

### ISSUE THREAD

**Issue by arkolbus** [swagger-api/swagger-codegen#7803]
##### Description
Using swagger-codegen 2.3.1 to generate nodejs-server, it appears that the generated code is looking in `service/` for the generated services, but the services are actually in `controllers/`

Output from trying to start the server:
```
PS D:\sandbox\petstore-2.3.1> node .\index.js
Error initializing middleware
Error: Cannot find module '../service/PetService'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\sandbox\petstore-2.3.1\controllers\Pet.js:4:11)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

My generated PetService.js is located at controllers/PetService.js.  I have no folder named 'service'.

##### Swagger-codegen version
I can reproduce this in v2.3.0 and v2.3.1.  It is working in v2.2.3

##### Swagger declaration file content or url
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml

##### Command line used for generation
`java -jar swagger-codegen-cli-2.3.1.jar generate -i .\petstore.yaml -l nodejs-server -o petstore-2.3.1\`

##### Steps to reproduce
1. Generate nodejs-server from petstore.yaml per above
2. Run `npm update` to install dependencies
3. Run `node .\index.js` to start the server
4. Error (documented above) is printed to console during startup

##### Related issues/PRs
I was unable to find any related issues

**Comment by arkolbus** [comment]
I think this is a duplicate of issue #6443

**Comment by wing328** [comment]
@arkolbus thanks for reporting the issue. We'll use #6443 for tracking.

Closing this one.
