### PR TITLE
ContentType selection fix for csharp.

### PR DESCRIPTION
**Pull request by alex-fisher**
Updated to reflect java implementation. Previously any request body of type string was having the content type overridden to 'application/json'.  This prevented custom json ContentTypes

### PR checklist

- [ x ] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ x ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ x ] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ x ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

https://github.com/swagger-api/swagger-codegen/issues/6629

### CODE REVIEW

**Comment by wing328** [comment]
@alex-fisher thanks for the fix. Please use 4-space instead of tab.

cc @mandrean @jimschubert

File: modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache [hunk 1]
```diff
@@ -165,24 +165,12 @@ namespace {{packageName}}.Client
...
-                if (postBody.GetType() == typeof(String))
-                {
-                    {{#netStandard}}
-                    request.AddParameter(new Parameter { Value = postBody, Type = ParameterType.RequestBody, ContentType = "application/json" });
-                    {{/netStandard}}
-                    {{^netStandard}}
-                    request.AddParameter("application/json", postBody, ParameterType.RequestBody);
-                    {{/netStandard}}
-                }
-                else if (postBody.GetType() == typeof(byte[]))
```
Comment (jimschubert) [inline modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache]: This check previously existed to support file inputs. Can you verify your change works when posting files?

Comment (alex-fisher) [reply modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache]: @jimschubert I implemented the 'UploadFile' test for the generated Petstore csharp api solution. The test passed and the api response was a 200.  Let me know if there is any further testing you would like me to do.

Comment (jimschubert) [reply modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache]: @alex-fisher I don't see that in this PR. Is it on another branch?

Comment (alex-fisher) [reply modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache]: This was done in the tests generated by the sdk and not in the actual testing suite.  Would you like me to add a permanent test for this?

Comment (jimschubert) [reply modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache]: Is it repeatable? If you share it here as a snippet, we can evaluate and either add it to this pr or to a later pr. It would be ideal as a permanent test.

Comment (alex-fisher) [reply modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache]: This is similar to the test I wrote to verify the upload functionality.  In my case I used an actual jpeg on my file system but for testing purposes a 'fake' file memory stream may suffice. 
```
[Test()]
public void TestFileUpload()
{
	PetApi petApi = new PetApi();
	long petId = 12312;

	using (var testStream = new MemoryStream(Encoding.UTF8.GetBytes("Test File Contents")))
	{
		var response = petApi.UploadFileWithHttpInfo(petId, null, testStream);
		Assert.AreEqual(response.StatusCode, (int)HttpStatusCode.OK);
		Assert.IsTrue(
			response.Data.Message.Contains("File uploaded to ./no_file_name_provided, 18 bytes"));
	}
}
``` 

After looking into this further it may make sense to test the ApiClient directly in ApiClientTests.cs:
```
[Test()]
public void TestFileUpload()
{
	ApiClient client = new ApiClient();
	long petId = 12312;

	var path = "/pet/{petId}/uploadImage";
	var queryParams = new List<KeyValuePair<string, string>>();
	object body = null;
	var headers = new Dictionary<string, string>() {{"Accept", "application/json"}};
	var formParams = new Dictionary<string, string>();
	var pathParams = new Dictionary<string, string>() {{"petId", petId.ToString()}};
	var contentType = "multipart/form-data";

	using (var testStream = new MemoryStream(Encoding.UTF8.GetBytes("Test File Contents")))
	{
		var response = (IRestResponse) client.CallApi(
			path,
			Method.POST,
			queryParams,
			body,
			headers,
			formParams,
			new Dictionary<string, FileParameter>()
			{
				{
					"file",
					client.ParameterToFile("file", testStream)
				}
			},
			pathParams,
			contentType);

		var apiResponse = new ApiResponse<ApiResponse>(
			(int) response.StatusCode,
			response.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
			(ApiResponse)
			client.Deserialize(response, typeof(ApiResponse)));

		Assert.AreEqual(apiResponse.StatusCode, (int) HttpStatusCode.OK);
		Assert.IsTrue(apiResponse.Data.Message.Contains("File uploaded to ./no_file_name_provided, 18 bytes"));
	}
}
```

Comment (wing328) [reply modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache]: @alex-fisher we do have Petstore integration tests for uploading files to Petstore servers and other operations but seems like they (partially) were removed somehow. I'll need to double check...

Comment (alex-fisher) [reply modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache]: Is there any further investigation I can do on my part for this request?

Comment (wing328) [reply modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache]: Let me add back the tests shortly. Stay tuned.

Comment (wing328) [reply modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache]: Tests added back https://github.com/swagger-api/swagger-codegen/pull/6663

Please rebase on the latest master to add the tests to this PR.

Comment (jimschubert) [reply modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache]: thanks for taking that down. I've had a rough week and not much time after work.

Comment (wing328) [reply modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache]: No worry :)

**Comment by wing328** [comment]
@alex-fisher I did a test after merging this PR into master (local) and got the following errors:
```
Client\ApiClient.cs(365,124): error CS0117: 'StringComparison' does not contain a definition for 'InvariantCultureIgnoreCase' [C:\projects\swagger-codegen-wh2wu\samples\client\petstore\csharp\SwaggerClientNetStandard\src\IO.Swagger\IO.Swagger.csproj]
Done Building Project "C:\projects\swagger-codegen-wh2wu\samples\client\petstore\csharp\SwaggerClientNetStandard\src\IO.Swagger\IO.Swagger.csproj" (default targets) -- FAILED.
Done Building Project "C:\projects\swagger-codegen-wh2wu\samples\client\petstore\csharp\SwaggerClientNetStandard\IO.Swagger.sln" (default targets) -- FAILED.
Build FAILED.
```

I wonder if you can take a look when you've time.

There are also trailing spaces in this line: https://github.com/swagger-api/swagger-codegen/pull/6633/files#diff-341919c3ab263078622fab0ceaec55eeR404 so please remove those in the next commit.

**Comment by wing328** [comment]
AppVeyor tests passed. Thanks for the PR, which has been merged into master 👍
