### PR TITLE
[TypeScript][Angular] fix date path parameters (#7476, #7302)

### LINKED ISSUE #7302: api paths decorated with :.+ produce invalid angular code
##### Description

If I have the following api path:

  /myservice/{myvar:.+}:

Then this produces invalid angular code with the typescript-angular plugin.

##### Swagger-codegen version

2.3.0

##### Swagger declaration file content or url

Any API path with: 
  /myservice/{myvar:.+}:

##### Command line used for generation
mvn clean compile

##### Steps to reproduce

Simply put that into your path and use the typescript-angular plugin to generate.  The default.service.ts generation is invalid:

${this.basePath}/myservice/${encodeURIComponent(String(myvar:.+))}`,

Produces the following ts compile errors:

[ERROR] src/app/api/default.service.ts(172,132): error TS1005: ',' expected.
[ERROR] src/app/api/default.service.ts(172,133): error TS1135: Argument expression expected.
[ERROR] src/app/api/default.service.ts(172,135): error TS1109: Expression expected.

We will have to regress to 2.2.3 version for the time being. The :.+ construct was working fine in 2.2.3 and enables the system to process variables with "extra" characters such as slashes and the like.

### LINKED ISSUE #7476: [typescript-angular2] Datetime parameters are not correctly formatted in request path
##### Description

I'm using codegen with an angular4 project.
I made an api endpoint with a datetime in the path like /line/{line:int}/exploitation/{xpdate:datetime}/incident
          

>               {  
>                   "name":"xpdate",
>                   "in":"path",
>                   "required":true,
>                   "type":"string",
>                   "format":"date-time"
>                },

The code generated for the previous snippet a datetime parameter is: 
`encodeURIComponent(String(xpdate))`
Result is like 'Sat%20Dec%2024%202016%2001%3A00%3A00%20GMT%2B0100%20(Paris%2C%20Madrid)'
and the request fails !

I noticed datetime parameter is right generated for a query parameters: 

>                {  
>                   "name":"StartDate",
>                   "in":"query",
>                   "required":true,
>                   "type":"string",
>                   "format":"date-time"
>                },

Generated code for query parameter is like: 
if (startDate !== undefined) {
            queryParameters = queryParameters.set('StartDate', <any>startDate.toISOString());
        }

##### Swagger-codegen version

2.3.1

##### Suggest a fix/enhancement

Generate specific method call for datatypes instead of generic toString() method.

### PR DESCRIPTION
**Pull request by macjohnny**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

fixes #7476, fixes #7302

```yaml
/pet/{birthday}/foo/{id:.+}:
    ...
      parameters:
        - name: birthday
          in: path
          type: string
          format: date-time
        - name: id
          in: path
          type: string
```
now results in 
```typescript
httpClient.get<Array<Pet>>(`${this.basePath}/pet/${encodeURIComponent(String(birthday.toISOString()))}/foo/${encodeURIComponent(String(id_))}`,
```
instead of 
```typescript
httpClient.get<Array<Pet>>(`${this.basePath}/pet/${encodeURIComponent(String(birthday))}/foo/${encodeURIComponent(String(id_))}`,
```

### CODE REVIEW

**Comment by macjohnny** [comment]
cc @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx

**Comment by macjohnny** [comment]
successfully tested with the following dummy api endpoint:
```
/pet/{birthday}/foo/{id:.+}:
    get:
      tags:
        - pet
      operationId: findPetsByStatusfoo
      produces:
        - application/xml
        - application/json
      parameters:
        - name: birthday
          in: path
          required: true
          type: string
          format: date-time
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          schema:
            type: array
            items:
              $ref: '#/definitions/Pet'
```

@arjuin can you confirm this resolves issue https://github.com/swagger-api/swagger-codegen/issues/7476 ?

@inthegarage can you confirm this resolves issue https://github.com/swagger-api/swagger-codegen/issues/7302 ?

**Comment by macjohnny** [comment]
cc @bedag-moo @defmonk0 @JohannesHoppe

**Comment by arjuin** [comment]
It resolves the issue.
Thanks.

**Comment by defmonk0** [comment]
I ran through the code, and it looks fine to me. Was a good catch and simple fix that didn't require heavy reworking.

My only concern would be that this explicitly only works with alphanumeric characters and underscores in parameter names. Anything else will be noticed and considered the end of the parameter name. Anything following will be considered some modifier to be left out. There's a variety of possibilities that this might be invalid for. Are any other characters allowed in swagger variable names? Can similar modifiers be before the parameter name?

I'm having trouble finding any documentation on the templating that swagger is supposed to support. For example, under what circumstances is this colon:regex syntax is valid? I don't wanna dive too deep without having a better understanding of the templating involved. Any input/direction here would be great.

**Comment by macjohnny** [comment]
@defmonk0 one more character that should be valid is the dollar sign `$`. 
Currently, however, it is replaced with an underscore `_` 
here
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractTypeScriptClientCodegen.java#L151
using this method here
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L3495

This leads e.g. to https://github.com/swagger-api/swagger-codegen/issues/7484

Maybe we could explicitly look for the colon `:` to find the end of the variable name, allowing any other character.

@wing328 do you have any docs to point us to in order to find out more about the valid syntax in path parameters?

**Comment by macjohnny** [comment]
@defmonk0 I updated the code as I suggested above in https://github.com/swagger-api/swagger-codegen/pull/7479#issuecomment-360699167 to explicitly look for a colon `:` as a path parameter variable name terminator, if existing. 
Moreover, I fixed handling parameters that come after a parameter with a colon / special character by resetting 
`skipThisAndSubsequentChars = false;` in https://github.com/swagger-api/swagger-codegen/pull/7479/files#diff-ad60e100e050d5ef52943803a2adc5fdR277

With this changes, I could successfully test with the following swagger definition:
```
  /pet/{birthday}/foo/{id:.+}/{bla_bla}/bar:
    get:
      tags:
        - pet
      operationId: findPetsByStatusfoo
      produces:
        - application/xml
        - application/json
      parameters:
        - name: birthday
          in: path
          required: true
          type: string
          format: date-time
        - name: id
          in: path
          required: true
          type: string
        - name: bla_bla
          in: path
          required: true
          type: string
          format: date-time
      responses:
        '200':
          schema:
            type: array
            items:
              $ref: '#/definitions/Pet'
```

**Comment by macjohnny** [comment]
@arjuin could you please test the newest code again and confirm this resolves issue #7476 ?
@inthegarage could you please test the newest code again and confirm this resolves issue #7302 ?

**Comment by defmonk0** [comment]
@macjohnny I definitely think that's a bit safer/future-proof, and the example looks good. If William doesn't have any particular input or documentation for additional possibilities that this misses, I think it should be fine. 👍

**Comment by macjohnny** [comment]
@defmonk0 thanks for your response. would you mind reviewing the code with the github review feature in the top right corner?
review

File: modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java [hunk 1]
```diff
@@ -246,6 +246,8 @@ public void postProcessParameter(CodegenParameter parameter) {
             // Prep a string buffer where we're going to set up our new version of the string.
             StringBuilder pathBuffer = new StringBuilder();
             StringBuilder parameterName = new StringBuilder();
+            /** Whether to skip characters inside curly braces */
+            Boolean skipThisAndSubsequentChars = false;
```
Comment (TiFu) [inline modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java]: Maybe use the primitive `boolean` type here and change the comment to the actual function of this variable?
Below it's not only used to skip chars in curly braces, but also to skip chars after a colon.

File: samples/client/petstore/typescript-angular-v2/npm/tsconfig.json [hunk 2]
```diff
@@ -5,7 +5,7 @@
         "noImplicitAny": false,
         "suppressImplicitAnyIndexErrors": true,
         "target": "es5",
-        "module": "es6",
+        "module": "commonjs",
```
Comment (TiFu) [inline samples/client/petstore/typescript-angular-v2/npm/tsconfig.json]: Is this change correct? Seems like it was introduced in another PR.

Comment (macjohnny) [reply samples/client/petstore/typescript-angular-v2/npm/tsconfig.json]: @TiFu yes, that's right, I guess this pops up since I had to re-generate all typescript files.

File: modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java (hunk 1 above)
Comment (macjohnny) [reply modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java]: @TiFu done, I updated the commend and changed the type to `boolean`

**Comment by inthegarage** [comment]
@macjohnny Yes I agree this change is fine and code produced will work in the other scenario. Sadly I cannot test the change at the moment as other changes in 2.4.0-SNAPSHOT have broken the generation of the code. I will document these issues in due course.

**Comment by macjohnny** [comment]
@inthegarage thanks for your feedback. could you specify what other issues you have with the current snapshot version? maybe we could include a quick fix in this PR

**Comment by inthegarage** [comment]
@macjohnny 
I will add further issues here:
https://github.com/swagger-api/swagger-codegen/issues/7535

**Comment by macjohnny** [comment]
@wing328 the issue reported by @inthegarage does not seem related to this PR.
Since this PR has been reviewed, it should be ready to be merged.

**Comment by inthegarage** [comment]
@macjohnny  no it's not related. I should get time to review the other issue later.

**Comment by wing328** [comment]
If no further comment/question on this PR, I'll merge it on coming Sunday.

cc @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx

**Comment by macjohnny** [comment]
Following the discussion in https://github.com/swagger-api/swagger-codegen/issues/7302, this PR should not be merged yet.

**Comment by macjohnny** [comment]
@wing328 the PR was reverted to comply with the discussion in #7302, so it should be ready to be merged now

**Comment by macjohnny** [comment]
@gualtierim would you like to port this change to the typescript-inversify generator, since you use the same logic there?

**Comment by gualtierim** [comment]
@macjohnny yes I will port this change

**Comment by macjohnny** [comment]
@wing328 can you merge this?

**Comment by macjohnny** [comment]
@wing328 the conflicts have been resolved, could you please merge this?

**Comment by wing328** [comment]
@macjohnny I've merged the PR into master. Thanks for the contribution.
