### PR TITLE
[Go] Fix operation files clobbering model files. [2.4.0]

### LINKED ISSUE #6942: master branch does not produce compilable go code.
##### Description

Trying to build a go client creates a go library that does not compile. Tried on master. When trying to build on 2.2.3, it produces working go code that does not have the missing API declaration.

##### Swagger-codegen version

Master

##### Swagger declaration file content or url

https://sftp.solace.com/download/VMR_SEMPV2_SCHEMA_YAML

##### Command line used for generation
```
java -jar ./swagger-codegen-cli.jar generate -i https://sftp.solace.com/download/VMR_SEMPV2_SCHEMA_YAML -l go -DpackageName=semp_client -o semp_client
```
##### Steps to reproduce

``` shell
$ java -jar ./swagger-codegen-cli.jar generate -i https://sftp.solace.com/download/VMR_SEMPV2_SCHEMA_YAML -l go -DpackageName=semp_client -o semp_client
$ cd semp_client
$ go get -v 
./about_api_response.go:15:8: undefined: AboutApi
```

##### Suggest a fix/enhancement

Clearly AboutApi is not created here, even though there are references of it everywhere.

### PR DESCRIPTION
**Pull request by antihax**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language. 

@antihax @bvwells 

### Fix operation files clobbering model files.
Prepend model_ to all model file names to operation groups with the same name from clobbering the model files. This should be a non-breaking change. This resolves #6942

### CODE REVIEW

**Comment by antihax** [comment]
@wing328 can you restart the travis build? It looks like it failed on a python test.

**Comment by wing328** [comment]
Restarted. All tests passed.
