### ISSUE TITLE
master branch does not produce compilable go code.

### ISSUE THREAD

**Issue by wari** [swagger-api/swagger-codegen#6942]
##### Description

Trying to build a go client creates a go library that does not compile. Tried on master. When trying to build on 2.2.3, it produces working go code that does not have the missing API declaration.

##### Swagger-codegen version

Master

##### Swagger declaration file content or url

https://sftp.solace.com/download/VMR_SEMPV2_SCHEMA_YAML

##### Command line used for generation
```
java -jar ./swagger-codegen-cli.jar generate -i https://sftp.solace.com/download/VMR_SEMPV2_SCHEMA_YAML -l go -DpackageName=semp_client -o semp_client
```
##### Steps to reproduce

``` shell
$ java -jar ./swagger-codegen-cli.jar generate -i https://sftp.solace.com/download/VMR_SEMPV2_SCHEMA_YAML -l go -DpackageName=semp_client -o semp_client
$ cd semp_client
$ go get -v 
./about_api_response.go:15:8: undefined: AboutApi
```

##### Suggest a fix/enhancement

Clearly AboutApi is not created here, even though there are references of it everywhere.

**Comment by wing328** [comment]
Closed via #7337 

Please pull the latest master to give it a try.

**Comment by wari** [comment]
@wing328 Tested, and gave it a look. I can now `go get` with no problems. ❤️ the `localVarOptionals map[string]interface{}` instead of the old style calls, which made things mandatory. Breaks the old API, but this is better!

**Comment by wing328** [comment]
@wari thanks for testing the latest to confirm it's working for you.
