### ISSUE TITLE
PHP server generation does not work

### ISSUE THREAD

**Issue by rickpelletier** [swagger-api/swagger-codegen#1000]
I am completely unable to get the [php generate server example](https://github.com/swagger-api/swagger-codegen/tree/master/samples/server-generator/php) to work.  

The first obvious issue is that `./bin/runscala.sh` does not even exist in master.

Additionally, If I try to execute `scala samples/server-generator/php/PHPServerGenerator.scala http://petstore.swagger.wordnik.com/api/api-docs special-key` directly I get this error:

```
/Users/richard/workspace/swagger-codegen/samples/server-generator/php/PHPServerGenerator.scala:17: error: not found: type BasicPHPGenerator
object PHPServerGenerator extends BasicPHPGenerator {
                                  ^
/Users/richard/workspace/swagger-codegen/samples/server-generator/php/PHPServerGenerator.scala:20: error: not found: value generateClient
  def main(args: Array[String]) = generateClient(args)
                                  ^
/Users/richard/workspace/swagger-codegen/samples/server-generator/php/PHPServerGenerator.scala:27: error: not found: value apiTemplateFiles
  apiTemplateFiles.clear
  ^
/Users/richard/workspace/swagger-codegen/samples/server-generator/php/PHPServerGenerator.scala:29: error: not found: value modelTemplateFiles
  modelTemplateFiles.clear
  ^
four errors found
```

If I'm following the instructions incorrectly could someone help me out?  Or if they're just out of date I'd be willing to update the documentation if someone could help me figure out how to execute it correctly.

**Comment by rickpelletier** [comment]
I think maybe the [README.md](https://github.com/swagger-api/swagger-codegen/tree/master/samples/server-generator/php) is out of date.  After poking around the java code for the generators, I was able to generate server files by using the same syntax as for client code but with a "language" of `silex`:

```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate   -i http://petstore.swagger.io/v2/swagger.json   -l silex   -o samples/server/petstore/php
```

**Comment by rickpelletier** [comment]
After digging into this further I've realized that this is already being worked on in the develop_2.0 branch (https://github.com/swagger-api/swagger-codegen/commit/ce40da0f7124d42611898ebe5e49a5aaa9af44e1).

**Comment by wing328** [comment]
@rickpelletier please let us know if you've any feedback for the PHP Silex generator. Thanks!
