### ISSUE TITLE
Java client uses dated jersey client libraries

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#949]
In integrating a jersey 2 server with the swagger java client, I ran into issues with the client library being incompatible with the server and causing a host of issues.  There should be a jersey 2.x-compatible client for java

**Comment by webron** [comment]
This may conflict with #862 if it ends up being merged.

**Comment by fehguy** [comment]
I think the right solution is to keep everything consistent except the ApiClient class, and let there be an option for each invoker

**Comment by phauer** [comment]
I run into the same problems. The generated API library uses jersey-client 1.1.8 and dropwizard-core (0.8.0) uses jersey-client 2.16. This causes a lot of NoSuchMethodError when I use my dropwizard application (for startup in a test) in conjunction with the generated API library in the same project. Due to the different groupId (com.sun.jersey and org.glassfish.jersey.core), I can't try to force a certain version (which probably won't work anyway).

Unfortunately, this issue really prevents the usage of the generated API library. At least I can't think of any workaround except starting the dropwizard application via the command line in my test. But I really like the idea behind swagger-codegen.

**Comment by wing328** [comment]
@phauer the latest java client allows you to specify the http library (see the `library` option):
```
swagger-codegen|master ⇒ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l java 

CONFIG OPTIONS
	modelPackage
	    package for generated models

	apiPackage
	    package for generated api classes

	invokerPackage
	    root package for generated code

	groupId
	    groupId in generated pom.xml

	artifactId
	    artifactId in generated pom.xml

	artifactVersion
	    artifact version in generated pom.xml

	sourceFolder
	    source folder for generated code

	localVariablePrefix
	    prefix for generated code members and local variables

	serializableModel
	    boolean - toggle "implements Serializable" for generated models

	library
	    library template (sub-template) to use:
	    <default> - HTTP client: Jersey client 1.18. JSON processing: Jackson 2.4.2
	    jersey2 - HTTP client: Jersey client 2.6
```
would that resolve the issue you reported above?

**Comment by phauer** [comment]
@wing328 That looks great. Thanks!
Unfortunately, there are still version conflicts between dropwizard 0.8.0 and the client generated by swagger-codegen 2.1.3:
Jersey 2.16 (dropwizard) vs Jersey 2.8 (swagger-codegen)
Jackson 2.5.1 vs Jackson 2.4.2

However, it doesn't make sense to bring the library versions into line with the ones of dropwizard, because dropwizard is just one possible use case of swagger-codegen. Moreover, due to new releases of dropwizard, it's a never-ending work. I guess it would be the best, if I don't include my dropwizard-service in my pom and start the executable jar instead. This way I avoid version conflicts.

But I thank you very much! I guess, this feature helps other users of swagger-codegen.

**Comment by wing328** [comment]
@xhh is the one who makes this possible.

Closing this issue.
