### PR TITLE
Add optional support for HttpClient

### LINKED ISSUE #6080: Update Typescript-Angular (as of 2.3.0) To use Angular 4.3 HTTPClient optionally
##### Description

VIA https://angular.io/guide/http

As of Angular 4.3 they have decided to create a new API for the HTTP client.  As such we should update the generated Typescript-Angular client to use the new API as the old API will be deprecated in the future.  I foresee people no updating their Angular version strictly for their swagger generated code so that's why I think this should optional post 2.3.0 and not required. 

The enhancement idea would be to either follow the 2.3.0 ngVersion flag and select 4.3 for the newly HTTP or to have another flag that signifies you want to use it.  I'd suggest sticking to the ngVersion way due to changes in dependencies needing to be made as well.

This issue was mostly made for tracking purposes so we don't forget.

### PR DESCRIPTION
**Pull request by bedag-moo**
Support HttpClient in addition to Http, clean up generated code

Fixes #6080 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### CODE REVIEW

**Comment by wing328** [comment]
cc @Vrolijkx @taxpon @sebastianhaas @kenisteward @TiFu

**Comment by bedag-moo** [comment]
@wing328: Can you clarify what up with these branches? I thought since most typescript commits were only in 2.3.0, I should base my PR on that branch to minimize merging pain when 2.3.0 is finally merged?

**Comment by sebastianhaas** [comment]
As the PR checklist says, you should
> File[d] the PR against the correct branch: master for non-breaking changes and 3.0.0 branch for breaking (non-backward compatible) changes.

**Comment by wing328** [comment]
@bedag-moo the latest master of 2.3.0 (snapshot) so that's why I updated the PR to file against master.

**Comment by bedag-moo** [comment]
Ah, 2.3.0 has already been merged! That would have been nice to know before starting work on this PR (Because 2.3.0 is not released yet, I had assumed that master would remain for 2.2.x releases, as has been the case for nearly a year now). 

Might I suggest describing the mapping between branches and releases on your contribution page? And to delete branches after merging them?

Meanwhile, I'll rebase my changes to master.

**Comment by kenisteward** [comment]
Agreed. I thought 2.3.0 wasn't merged yet as well

**Comment by bedag-moo** [comment]
Rebase complete  (I had to do it manually, because everything had been moved to a different directory in the meantime).

**Comment by topce** [comment]
@bedag-moo Nice work.
One small issue for response type blob it does not compile 
`return this.httpClient.get<any>(`${this.basePath}/content/bulk`, {
            params: queryParameters,
            headers: headers,
            responseType: "blob",
            withCredentials: this.configuration.withCredentials,
        });`

tsc errror is 

 error TS2345: Argument of type '{ params: HttpParams; headers: HttpHeaders; responseType: "blob"; withCredentials: bool
ean | unde...' is not assignable to parameter of type '{ headers?: HttpHeaders | undefined; observe?: "body" | undefined; params?: HttpParams | undefine...'.
  Type '{ params: HttpParams; headers: HttpHeaders; responseType: "blob"; withCredentials: boolean | unde...' is not assignable to type '{ headers?: HttpHeaders | undefined;
observe?: "body" | undefined; params?: HttpParams | undefine...'.
    Types of property 'responseType' are incompatible.
      Type '"blob"' is not assignable to type '"json" | undefined'.
but code bellow works (removed <any>)
`return this.httpClient.get(`${this.basePath}/content/bulk`, {
            params: queryParameters,
            headers: headers,
            responseType: "blob",
            withCredentials: this.configuration.withCredentials,
        });`

**Comment by bedag-moo** [comment]
Thanks for the bug report; should be fixed now.

**Comment by wing328** [comment]
> Might I suggest describing the mapping between branches and releases on your contribution page? And to delete branches after merging them?

Definitely. Let me try this weekend.

File: modules/swagger-codegen/src/main/java/io/swagger/codegen/utils/SemVer.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
+package io.swagger.codegen.utils;
```
[the remark this answers is not in the document]
Comment (sebastianhaas) [reply modules/swagger-codegen/src/main/java/io/swagger/codegen/utils/SemVer.java]: I'd also vote for that :)

**Comment by kenisteward** [comment]
Did we make sure that this only applies in angular 4.3 and update the peer
dependencies as such ?

**Comment by sebastianhaas** [comment]
@kenisteward check out [this line](https://github.com/swagger-api/swagger-codegen/pull/6295/files#diff-ad60e100e050d5ef52943803a2adc5fdR115).

**Comment by kenisteward** [comment]
I missed the Ng version check. :) I'm very happy with this change

File: modules/swagger-codegen/src/main/java/io/swagger/codegen/utils/SemVer.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (bedag-moo) [reply modules/swagger-codegen/src/main/java/io/swagger/codegen/utils/SemVer.java]: Done. It is the first unit test in this package.

**Comment by wing328** [comment]
> Definitely. Let me try this weekend.
 
UPDATE: renamed 2.3.0 to 2.3.0_BACKUP_ONLY (to keep the git log for changes made to 2.3.0)

**Comment by wing328** [comment]
Restarted Travis CI job. Will merge after the test passes.

**Comment by macjohnny** [comment]
@bedag-moo it seems there are some conflicts with the changes introduced in https://github.com/swagger-api/swagger-codegen/pull/6525

I suggest you try to adapt your PR to conform with the fixes introduced in https://github.com/swagger-api/swagger-codegen/pull/6525, as replacing path-parameters with their value without url-escaping can lead to problems, see https://github.com/swagger-api/swagger-codegen/issues/6524

**Comment by krizic** [comment]
Generated functions are always having a trailing comma at the end! Please provide the fix.

```
getBillingInformation(start: Date, end: Date,): Observable<Array<BillingInformation>>{}
downloadLogoForCompany(companyId: string, fetchThumb: boolean,): Observable<ArrayBuffer>{}
...
```

**Comment by sebastianhaas** [comment]
I‘ll try to provide Angular Integration Tests this week so we can avoid these kind of issues.

**Comment by wing328** [comment]
@bedag-moo I wonder if you can rebase on the latest master to resolve the merge conflicts (sorry I should have merged yours first)

**Comment by kenisteward** [comment]
@krizic is this due to these changes or outside of these changes?  If it is outside these changes probably better to make a different issue.

File: modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache [hunk 2]
```diff
@@ -86,12 +79,8 @@ export class {{classname}} {
...
      {{#allParams}}* @param {{paramName}} {{description}}
      {{/allParams}}*/
-{{^isResponseFile}}
-    public {{nickname}}({{#allParams}}{{paramName}}{{^required}}?{{/required}}: {{{dataType}}}, {{/allParams}}extraHttpRequestParams?: any): Observable<{{#returnType}}{{{returnType}}}{{/returnType}}{{^returnType}}{}{{/returnType}}> {
-{{/isResponseFile}}
-{{#isResponseFile}}
-    public {{nickname}}({{#allParams}}{{paramName}}{{^required}}?{{/required}}: {{{dataType}}}, {{/allParams}}extraHttpRequestParams?: any): Observable<{{#returnType}}{{{returnType}}}|undefined{{/returnType}}{{^returnType}}{}{{/returnType}}> {
-{{/isResponseFile}}
+    {{! if you change this method signature, also change the version below }}
+    public {{nickname}}({{#allParams}}{{paramName}}{{^required}}?{{/required}}: {{{dataType}}}, {{/allParams}}{{^useHttpClient}}extraHttpRequestParams?: RequestOptionsArgs{{/useHttpClient}}): Observable<{{#returnType}}{{{returnType}}}{{#isResponseTypeFile}}|undefined{{/isResponseTypeFile}}{{/returnType}}{{^returnType}}{}{{/returnType}}> {
```
Comment (krizic) [inline modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache]: This causes to always have a trailing comma in the end of all of the parameters.

Comment (krizic) [reply modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache]: As mentioned above it produces this result:
```
getBillingInformation(start: Date, end: Date,): Observable<Array<BillingInformation>>{}
downloadLogoForCompany(companyId: string, fetchThumb: boolean,): Observable<ArrayBuffer>{}
```

Comment (kenisteward) [reply modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache]: Yup that definitely needs to be fixed then.

**Comment by krizic** [comment]
`CRITICAL` : PATCH request is missing body parameter so it sends the whole httpParams as the body! 

```
    return this.httpClient.patch<any>(`${this.basePath}v1/risk`, {
      params:          queryParameters,
      headers:         headers,
      withCredentials: this.configuration.withCredentials,
    });
```
actual signature of httpClient.Patch:
```
    patch(url: string, body: any | null, options?: {}): Observable<Object>;
```

File: modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache (hunk 2 above)
Comment (wing328) [reply modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache]: @krizic thanks for testing the change.

I think the following should fix the issue
```
    public {{nickname}}({{#allParams}}{{paramName}}{{^required}}?{{/required}}: {{{dataType}}}{{#hasMore}}, {{/hasMore}}{{/allParams}}{{^useHttpClient}}, extraHttpRequestParams?: RequestOptionsArgs{{/useHttpClient}}): Observable<{{#returnType}}{{{returnType}}}{{#isResponseTypeFile}}|undefined{{/isResponseTypeFile}}{{/returnType}}{{^returnType}}{}{{/returnType}}> {
 ```

When you've time, I wonder if you can give it a try by replacing line 83 with it.

cc @bedag-moo

Comment (krizic) [reply modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache]: I can confirm this is still an issue, and if you see the code it is obvious that in case that `useHtpClient` flag is true he WON'T add last method parameter (extraHttpRequestParams) effectively leaving method signature to always end with `,`.

`{{^useHttpClient}}*extraHttpRequestParams?:RequestOptionsArgs{{/useHttpClient}}`

Comment (krizic) [reply modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache]: @wing328 thanks for providing a quick solution!

Comment (wing328) [reply modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache]: I added `{{#hasMore}}, {{/hasMore}}` to skip "," for the last parameter. Are you using `-t` parameter to supply the customized templates with the fix?

Comment (wing328) [reply modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache]: Otherwise, you will need to do a "mvn clean package" to recompile the JAR.

Comment (krizic) [reply modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache]: @wing328 you are right. I wasn't cleaning bins. Works now, thanks for the solution again. I hope this gets merged soon

Comment (wing328) [reply modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache]: @krizic np. Thanks for confirming the fix works.

**Comment by bedag-moo** [comment]
Yes, I really would have preferred you to merge my changes first:

- I can not merge or rebase current master, because 3ac2b803f972d3919f1b8d04e0b32ef20613b15d removed and added a file differing only in file name case in a single commit, making it impossible to apply this commit on a case-insensitive filesystem (windows). Fortunately, there were no conflicts after this point.
- There is a merge conflict with #6454, whose intent is poorly documented (why would I set an accept header to what the server supports? The purpose of the accept header is telling the server what the *client* accepts!), and implemented very strangely (Why set the content type header to JSON, but only when posting a form? forms are never JSON ...). Since I see no value in this code, I have removed it. If you see a value, feel free to add it back in after fixing its bugs.
- There was a merge conflict with #6524, but at least here the intent was clear and the implementation sound, so adapting it was easy.

Please merge soon ...

**Comment by bedag-moo** [comment]
Oh no, there was yet another conflict behind the commit that can not be applied on windows ...

@wing328 : Can you fix that one?

**Comment by macjohnny** [comment]
@bedag-moo 
> There is a merge conflict with #6454, whose intent is poorly documented (why would I set an accept header to what the server supports? The purpose of the accept header is telling the server what the client accepts!), and implemented very strangely (Why set the content type header to JSON, but only when posting a form? forms are never JSON ...). Since I see no value in this code, I have removed it. If you see a value, feel free to add it back in after fixing its bugs.

I totally agree with you. The PR #6454 also resulted in a new bug: https://github.com/swagger-api/swagger-codegen/issues/6588, which would be fixed by merging your PR #6295

@wing328 please merge this PR as soon as possible

**Comment by wing328** [comment]
> @wing328 : Can you fix that one? You should be able to push to my branch.

Fixed but now encounter another issue due to methods with no argument, which result in the following errors:
```
api/store.service.ts(87,25): error TS1138: Parameter declaration expected.
api/store.service.ts(160,37): error TS1138: Parameter declaration expected.
api/user.service.ts(168,23): error TS1138: Parameter declaration expected.
api/user.service.ts(373,35): error TS1138: Parameter declaration expected.
```

I'm trying to come up with a fix.

**Comment by macjohnny** [comment]
@wing328 isn't this related to https://github.com/swagger-api/swagger-codegen/pull/6295#pullrequestreview-65826900 ?

**Comment by wing328** [comment]
@bedag-moo yup and I got a fix. Testing it now

**Comment by wing328** [comment]
After fixing that issue, now I got the following errors when running `npm run build`:
```
api/pet.service.ts(272,77): error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
api/pet.service.ts(380,77): error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
api/pet.service.ts(468,77): error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
api/pet.service.ts(521,77): error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
```

**Comment by wing328** [comment]
Fixed wth `String()` and the CI tests passed: https://travis-ci.org/swagger-api/swagger-codegen/builds/281593760

**Comment by wing328** [comment]
82b6e81 has the fixes for the issues mentioned above.

Please review when you've time.

cc @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx

**Comment by kenisteward** [comment]
@wing328 I looked over the string() addition and it looks safe. If that's all you needed I approve .  On my phone so I cant tell how to approve a change haha

**Comment by wing328** [comment]
@kenisteward thanks for reviewing the change. Have a nice weekend!

**Comment by xmeng1** [comment]
+1

**Comment by kenisteward** [comment]
This is already possible with 2.3.0

**Comment by takahashi64** [comment]
Is it possible to get swagger codegen cli to set useHttpClient to false?

**Comment by kenisteward** [comment]
It is set to false by default

**Comment by kenisteward** [comment]
It's set based on version you provide actually sorry. So just define with
any version under 4.3
